domain: multipass.run

image: prod-comms.docker-registry.canonical.com/multipass.run

env:
  - name: SENTRY_DSN
    value: https://a08a5f107a674535ad7637c82265f977@sentry.is.canonical.com//34

useProxy: false

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'multipass.run' ) {
      rewrite ^ https://multipass.run$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
